# Generated by Django 4.0.4 on 2022-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='image_url',
            field=models.URLField(max_length=255),
        ),
    ]
